import type {
  IrConst,
  IrEnumDeclaration,
  IrFunction,
  IrGlobal,
  IrInstruction,
  IrOperand,
  IrProgram,
  IrStructDeclaration,
  IrTerminator,
  IrType,
} from "@/ir/types";

export interface CEmitOptions {
  runtimeHeader?: string;
}

interface FunctionEmitContext {
  localNames: Map<string, string>;
  tempNames: Map<string, string>;
  globalNames: Map<string, string>;
  paramIds: Set<string>;
  multiBlock: boolean;
}

const defaultRuntimeHeader = "../runtime/dist/vek_runtime.h";

export function emitC(program: IrProgram, options: CEmitOptions = {}): string {
  const runtimeHeader = options.runtimeHeader ?? defaultRuntimeHeader;
  const lines: string[] = [
    "/* generated by vekc */",
    "#include <stdbool.h>",
    "#include <stdint.h>",
    "#define VEK_RUNTIME_IMPLEMENTATION",
    `#include "${runtimeHeader}"`,
    "",
  ];

  const structs = program.declarations.filter(
    (declaration): declaration is IrStructDeclaration =>
      declaration.kind === "struct_decl",
  );

  for (const s of structs) {
    lines.push(...emitStructTypedef(s));
  }
  if (structs.length > 0) lines.push("");

  const enums = program.declarations.filter(
    (declaration): declaration is IrEnumDeclaration =>
      declaration.kind === "enum_decl",
  );

  for (const e of enums) {
    lines.push(...emitEnumTypedef(e));
  }
  if (enums.length > 0) lines.push("");

  const globals = program.declarations.filter(
    (declaration): declaration is IrGlobal => declaration.kind === "global",
  );
  const globalNames = new Map(
    globals.map((global) => [global.id, cGlobalName(global.linkName)]),
  );

  for (const global of globals) {
    lines.push(emitGlobalDeclaration(global, globalNames));
  }
  if (globals.length > 0) lines.push("");

  const functions = program.declarations.filter(
    (declaration): declaration is IrFunction =>
      declaration.kind === "function" && declaration.body === "defined",
  );

  for (const fn of functions) {
    lines.push(`${functionPrototype(fn)};`);
  }
  if (functions.length > 0) lines.push("");

  for (const fn of functions) {
    lines.push(...emitFunction(fn, globalNames), "");
  }

  const entry = program.entry
    ? functions.find((fn) => fn.id === program.entry)
    : undefined;
  if (entry) lines.push(...emitMainWrapper(entry));

  return `${lines.join("\n").trimEnd()}\n`;
}

function functionPrototype(fn: IrFunction): string {
  const params = fn.params
    .map((param) => `${emitType(param.type)} ${cLocalName(param.local)}`)
    .join(", ");
  return `static ${emitType(fn.signature.returnType)} ${cFunctionName(fn.linkName)}(${
    params || "void"
  })`;
}

function emitGlobalDeclaration(
  global: IrGlobal,
  globalNames: Map<string, string>,
): string {
  const name = requireGlobal(globalNames, global.id);
  const type = emitType(global.type);
  const init = global.initializer ? ` = ${emitConst(global.initializer)}` : "";
  const qualifier = global.mutable ? "" : "const ";

  if (!global.mutable && type.endsWith("*")) {
    return `static ${type} const ${name}${init};`;
  }
  return `static ${qualifier}${type} ${name}${init};`;
}

function emitFunction(
  fn: IrFunction,
  globalNames: Map<string, string>,
): string[] {
  const multiBlock = fn.blocks.length > 1;
  const context: FunctionEmitContext = {
    localNames: new Map(
      fn.locals.map((local) => [local.id, cLocalName(local.id)]),
    ),
    tempNames: new Map(),
    globalNames,
    paramIds: new Set(fn.params.map((param) => param.local)),
    multiBlock,
  };
  const lines = [`${functionPrototype(fn)} {`];

  for (const local of fn.locals) {
    if (context.paramIds.has(local.id)) continue;
    lines.push(`  ${emitType(local.type)} ${cLocalName(local.id)};`);
  }

  for (const block of fn.blocks) {
    if (multiBlock) {
      lines.push(`${cBlockLabel(block.id)}:`);
    }
    for (const instruction of block.instructions) {
      lines.push(`  ${emitInstruction(instruction, context)}`);
    }
    if (block.terminator) {
      for (const line of emitTerminator(block.terminator, context)) {
        lines.push(`  ${line}`);
      }
    }
  }

  lines.push("}");
  return lines;
}

function emitInstruction(
  instruction: IrInstruction,
  context: FunctionEmitContext,
): string {
  if (instruction.kind === "assign") {
    return `${requireLocal(context, instruction.target)} = ${emitOperand(
      instruction.value,
      context,
    )};`;
  }

  if (instruction.kind === "binary") {
    const target = declareTemp(context, instruction.target);
    return `${emitType(instruction.type)} ${target} = ${emitOperand(
      instruction.left,
      context,
    )} ${instruction.operator} ${emitOperand(instruction.right, context)};`;
  }

  if (instruction.kind === "unary") {
    const target = declareTemp(context, instruction.target);
    return `${emitType(instruction.type)} ${target} = ${
      instruction.operator
    }${emitOperand(instruction.argument, context)};`;
  }

  if (instruction.kind === "call") {
    const call = `${emitOperand(instruction.callee, context)}(${instruction.args
      .map((arg) => emitOperand(arg, context))
      .join(", ")})`;
    if (!instruction.target) return `${call};`;
    const target = declareTemp(context, instruction.target);
    return `${emitType(instruction.type)} ${target} = ${call};`;
  }

  if (instruction.kind === "construct_enum") {
    const target = declareTemp(context, instruction.target);
    const enumType = emitType(instruction.type);
    if (instruction.payload.length === 0) {
      return `${enumType} ${target} = (${enumType}){ .tag = ${instruction.tag} };`;
    }
    const payloadFields = instruction.payload
      .map(
        (p, i) =>
          `.data.${instruction.variant}._${i} = ${emitOperand(p, context)}`,
      )
      .join(", ");
    return `${enumType} ${target} = (${enumType}){ .tag = ${instruction.tag}, ${payloadFields} };`;
  }

  if (instruction.kind === "get_tag") {
    const target = declareTemp(context, instruction.target);
    return `${emitType(instruction.type)} ${target} = ${emitOperand(instruction.object, context)}.tag;`;
  }

  if (instruction.kind === "get_enum_payload") {
    const target = declareTemp(context, instruction.target);
    return `${emitType(instruction.type)} ${target} = ${emitOperand(instruction.object, context)}.data.${instruction.variant}._${instruction.index};`;
  }

  if (instruction.kind === "construct_struct") {
    const target = declareTemp(context, instruction.target);
    const fields = instruction.fields
      .map((f) => `.${f.name} = ${emitOperand(f.value, context)}`)
      .join(", ");
    return `${emitType(instruction.type)} ${target} = (${emitType(instruction.type)}){ ${fields} };`;
  }

  if (instruction.kind === "get_field") {
    const target = declareTemp(context, instruction.target);
    return `${emitType(instruction.type)} ${target} = ${emitOperand(instruction.object, context)}.${instruction.field};`;
  }

  if (instruction.kind === "set_field") {
    return `${requireLocal(context, instruction.target)}.${instruction.field} = ${emitOperand(instruction.value, context)};`;
  }

  if (instruction.kind === "store_global") {
    return `${requireGlobal(context.globalNames, instruction.globalId)} = ${emitOperand(instruction.value, context)};`;
  }

  const target = declareTemp(context, instruction.target);
  return `${emitType(instruction.type)} ${target} = (${emitType(
    instruction.type,
  )})${emitOperand(instruction.value, context)};`;
}

function emitTerminator(
  terminator: IrTerminator,
  context: FunctionEmitContext,
): string[] {
  if (terminator.kind === "unreachable") return ["__builtin_unreachable();"];

  if (terminator.kind === "return") {
    if (!terminator.value || isVoidOperand(terminator.value))
      return ["return;"];
    return [`return ${emitOperand(terminator.value, context)};`];
  }

  if (terminator.kind === "branch") {
    return [`goto ${cBlockLabel(terminator.target)};`];
  }

  if (terminator.kind === "cond_branch") {
    const cond = emitOperand(terminator.condition, context);
    const thenLabel = cBlockLabel(terminator.thenTarget);
    const elseLabel = cBlockLabel(terminator.elseTarget);
    return [`if (${cond}) goto ${thenLabel}; else goto ${elseLabel};`];
  }

  if (terminator.kind === "switch") {
    const val = emitOperand(terminator.value, context);
    const lines: string[] = [`switch (${val}) {`];
    for (const c of terminator.cases) {
      lines.push(
        `  case ${emitConst(c.value)}: goto ${cBlockLabel(c.target)};`,
      );
    }
    lines.push(`  default: goto ${cBlockLabel(terminator.defaultTarget)};`);
    lines.push("}");
    return lines;
  }

  return ["/* unknown terminator */"];
}

function emitMainWrapper(entry: IrFunction): string[] {
  const call = `${cFunctionName(entry.linkName)}()`;
  if (
    entry.signature.returnType.kind === "primitive" &&
    entry.signature.returnType.name === "void"
  ) {
    return ["int main(void) {", `  ${call};`, "  return 0;", "}"];
  }
  return ["int main(void) {", `  return ${call};`, "}"];
}

function emitOperand(operand: IrOperand, context: FunctionEmitContext): string {
  if (operand.kind === "const") return emitConst(operand.value);
  if (operand.kind === "local") return requireLocal(context, operand.id);
  if (operand.kind === "temp") return requireTemp(context, operand.id);
  if (operand.kind === "global")
    return requireGlobal(context.globalNames, operand.id);
  if (operand.name === "panic") return "__vek_panic_cstr";
  return cFunctionName(operand.name);
}

function emitConst(value: IrConst): string {
  if (value.kind === "int" || value.kind === "float") return value.value;
  if (value.kind === "string") return JSON.stringify(value.value);
  if (value.kind === "bool") return value.value ? "true" : "false";
  if (value.kind === "null") return "0";
  return "";
}

function emitStructTypedef(s: IrStructDeclaration): string[] {
  const fields = s.fields.map((f) => `  ${emitType(f.type)} ${f.name};`);
  return [`typedef struct {`, ...fields, `} ${cStructName(s.linkName)};`];
}

function emitEnumTypedef(e: IrEnumDeclaration): string[] {
  const payloadVariants = e.variants.filter((v) => v.payloadTypes.length > 0);
  const lines: string[] = [`typedef struct {`, `  int32_t tag;`];
  if (payloadVariants.length > 0) {
    lines.push(`  union {`);
    for (const v of payloadVariants) {
      const fields = v.payloadTypes
        .map((t, i) => `${emitType(t)} _${i};`)
        .join(" ");
      lines.push(`    struct { ${fields} } ${v.name};`);
    }
    lines.push(`  } data;`);
  }
  lines.push(`} ${cEnumName(e.linkName)};`);
  return lines;
}

function emitType(type: IrType): string {
  if (type.kind === "named") {
    return type.decl === "enum" ? cEnumName(type.name) : cStructName(type.name);
  }
  if (type.kind !== "primitive") {
    throw new Error(`C emission does not support type '${type.kind}' yet.`);
  }

  switch (type.name) {
    case "i8":
      return "int8_t";
    case "i16":
      return "int16_t";
    case "i32":
      return "int32_t";
    case "i64":
      return "int64_t";
    case "u8":
      return "uint8_t";
    case "u16":
      return "uint16_t";
    case "u32":
      return "uint32_t";
    case "u64":
      return "uint64_t";
    case "f16":
      throw new Error("C emission does not support f16 yet.");
    case "f32":
      return "float";
    case "f64":
      return "double";
    case "bool":
      return "bool";
    case "void":
      return "void";
    case "string":
      return "const char *";
    case "null":
      return "void *";
  }
}

function cFunctionName(name: string): string {
  return `__vek_fn_${sanitizeName(name)}`;
}

function cLocalName(id: string): string {
  return `v${id.replace(/^local\./, "")}`;
}

function cTempName(id: string): string {
  return `t${id.replace(/^tmp\./, "")}`;
}

function cBlockLabel(id: string): string {
  return id.replace(/\./g, "_");
}

function cGlobalName(name: string): string {
  return `__vek_global_${sanitizeName(name)}`;
}

function sanitizeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^([0-9])/, "_$1");
}

function cStructName(name: string): string {
  return `__vek_struct_${sanitizeName(name)}`;
}

function cEnumName(name: string): string {
  return `__vek_enum_${sanitizeName(name)}`;
}

function declareTemp(context: FunctionEmitContext, id: string): string {
  const name = cTempName(id);
  context.tempNames.set(id, name);
  return name;
}

function requireLocal(context: FunctionEmitContext, id: string): string {
  const name = context.localNames.get(id);
  if (!name) throw new Error(`Unknown local '${id}' during C emission.`);
  return name;
}

function requireTemp(context: FunctionEmitContext, id: string): string {
  const name = context.tempNames.get(id);
  if (!name) throw new Error(`Unknown temp '${id}' during C emission.`);
  return name;
}

function requireGlobal(globalNames: Map<string, string>, id: string): string {
  const name = globalNames.get(id);
  if (!name) throw new Error(`Unknown global '${id}' during C emission.`);
  return name;
}

function isVoidOperand(operand: IrOperand): boolean {
  return (
    operand.kind === "const" &&
    operand.value.kind === "void" &&
    operand.type.kind === "primitive" &&
    operand.type.name === "void"
  );
}
